name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master  # ここはデフォルトブランチ名に応じて変更（例: main）

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 必要な Node.js のバージョンを指定

      - name: Install dependencies
        run: npm ci  # 依存関係をインストール

      - name: Build the project
        run: npm run build  # ビルドを実行

      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Hosting-Action@v2.0.0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: muscle-health-auth
